export const AUTH_LOGIN_START = 'AUTH_LOGIN_START'
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"

export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const AUTH_GOOGLE_LOGIN_START = "AUTH_GOOGLE_LOGIN_START"
export const AUTH_GOOGLE_LOGIN_SUCCESS = "AUTH_GOOGLE_LOGIN_SUCCESS"
export const AUTH_GOOGLE_LOGIN_FAILURE = "AUTH_GOOGLE_LOGIN_FAILURE"

export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START"
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE"